### ISSUE TITLE
Quirky behaviour of setting scale ranges

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#27] opened 2022-04-22 09:25 UTC
Within AverageR and TimeR we can impose a restriction that all values must be within a certain (0-1 or 0-100). This is NOT a scale option rather it alters modelled values and constrain these within such ranges. For instance, if one applies the 0-100 restriction and the model has estimates of 105 or -3, these will be re-calculated as 100 and 0, respectively.

Separate, from the above the user can set ranges for min and max scale values. This setting is purely for visualization and does not alter modelled values. It merely sets the range for colour coding of the maps.

I was trying to generate a TimeR model using this dataset (I have used this several time before): 
[combined fauna2.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/8539505/combined.fauna2.xlsx)

Model settings shown in this video (also used to report bug #28 ): https://youtu.be/_C2kZQP8PbA

While applying a constraint and then setting the colour scale the app entered a non-ending loop where it would go through various scale values. See here: https://youtu.be/P7sfvsedfww

This was an error that I reported some months ago. Prior to this the app was working as expected on the same dataset.

**Comment by jroachell15** [comment] 2022-05-05 08:05
@isomemo 

Hi Ricardo, 
TIMER- not working:
- i have not been able to reproduce this: on our side, the beta version was able to upload the dataset you specified `combinedFauna2`, and a map was rendered. This is the result: 
![image](https://user-images.githubusercontent.com/73887426/166882346-04484533-3595-4c3b-bcb5-3cfdbc216945.png)
- could you please test this again on your end?


Scale values on the map:
![image](https://user-images.githubusercontent.com/73887426/166883634-3ee923f5-8f57-49bd-8780-6d06e9eb7410.png)
I can confirm that when clicking the `restrict range dependent variable` the scale did not correspond, but when i click on from `1-100` to `0-1`, then it works. We will look into this more and try to fix this.

thanks for the reporting.

**Comment by mgross** [comment] 2022-05-07 09:43
I tested it and everything works as intended, not sure what the issue is here.  When clicking on the "restrict range dependent variable" , the scale doesn't respond, yes. But why should it? You can set the scale to 0 to 0.2 and restrict the range to 0-1 (e.g. to set negative values to 0). Why should the latter change the scale. I think everything works fine here.

**Comment by isomemo** [comment] 2022-05-07 10:00
Ok on TimeR working now! As you saw from the video it was not working when I tested it although now it does. Could this have been related to server overload?

As for the bug with the restriction, I was referring to the endless loop that this generates. As Marcus, mentioned the restriction is a estimate option while the scale is the selected interval and I should be able to set these separately.  The loop bug is shown in this video: https://www.youtube.com/watch?v=P7sfvsedfww

**Comment by arunge** [comment] 2022-05-10 13:44
@mgross @jroachell15 I will tackle the rerendering issue within #34

**Comment by arunge** [comment] 2022-06-15 08:27
@isomemo Since this bug is due to too many rerenderings of the map I shift it to the future tasks. By restructuring the UI within #34 this bug will very certainly be fixed.

**Comment by isomemo** [comment] 2022-06-15 08:28
Ok! Please remember to add this to the new contract!

**Comment by arunge** [comment] 2022-11-08 08:59
@isomemo [Version 22.11.1](https://github.com/Pandora-IsoMemo/iso-app/pull/75#issue-1420559933) on the [beta](https://isomemoapp.com/app/iso-memo-app-beta) branch fixes the Bugs mentioned [above](https://github.com/Pandora-IsoMemo/iso-app/issues/27#issue-1212071960).

Regarding:
> This is NOT a scale option rather it alters modelled values and constrain these within such ranges

please note, I did not change any logic, how values are calculated. I only changed the reactive behavior. In the context of #34 I encapsulated the functionalities for the color scale into a separate module, which is now applied in all modelling tabs with the respective features, e.g.
| TimeR | LocateR |
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/200516405-1fe9a0a0-b724-4d6e-bc79-17e25dbd678d.png)|![image](https://user-images.githubusercontent.com/16759098/200516964-4a372c34-b6ee-4c68-bb38-8cfe0f94f404.png)|

Please, test the settings for the color scale and check if all is working as expected.

Next, I would like to merge the current beta version into the main version. This would add **all** changes from version 22.09.1 on (documented [here](https://github.com/Pandora-IsoMemo/iso-app/blob/beta/NEWS.md#mpiisoapp-22091)) to the [main app](https://isomemoapp.com/app/iso-memo-app), including Bug fixes for #62, #63, #67, #44, #27. Is that ok for you?

Afterwards, I would start adding features regarding the [merging of files](https://github.com/Pandora-IsoMemo/iso-app/issues/37) into the beta version, such that you can test those features and that we can discuss how to implement open points regarding the merging in a future meeting.

**Comment by arunge** [comment] 2022-11-08 09:44
Note: There are new features that you did not confirm yet (the issues are assigned to you): #8, #67

Should we wait with merging those into the main app until you had the time to test them?

**Comment by isomemo** [comment] 2022-12-02 10:32
@arunge Yes, please merge!

**Comment by arunge** [comment] 2022-12-05 18:42
The bug is fixed, the release from beta to the main is documented in following issue: https://github.com/Pandora-IsoMemo/iso-app/issues/80
So, I close here.

**Closed by arunge** 2022-12-05 18:42 UTC
Labels: bug, IsoMemo App, 2022-WP2-2
