### ISSUE TITLE
Bugs with mapping

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#24] opened 2022-04-19 14:14 UTC
Several issues with mapping in IsoMemo app. Listed below and shown in this video: https://youtu.be/pi6w_9blU3U

In regular version: size of points shown in app are larger in the export

Both versions: when show/hide north arrow/scale/logo the entire map is moved
weird behaviour with visibility of export button

Beta version:
applying coordinate values should not be dynamic! Add an "Apply coordinates" button
the show/hide button is for the Pandora database square (a new logo has been added)
Most important when exporting a map a different area of the map is shown and the points are not visible (we had this bug before)

**Comment by jroachell15** [comment] 2022-04-20 06:53
@isomemo yes we are going over and trying to reproduce the bugs now. thanks Ricardo.

**Comment by arunge** [comment] 2022-04-21 09:03
@isomeme regarding:

> the show/hide button is for the Pandora database square (a new logo has been added)

Obviously, there was a misunderstanding with:
> Option to hide/show Pandora/IsoMemo labels on the top left of the interactive map.

I thought a logo should be added. Of course, we can change this to show/hide the legend.

**Comment by arunge** [comment] 2022-04-21 09:29
> Both versions: when show/hide north arrow/scale/logo the entire map is moved

I can confirm this behaviour. The zoom and the center is reseted always when "include Scale" or "Include North Arrow" is changed.
The updates of zoom and the center must be fixed. Unfortunately this requires some refactoring, only adding the center and zoom to the drawing function inside the rendering of the map leads to unintended reloadings of the map. I must first figure out how to solve this.

**Comment by arunge** [comment] 2022-04-21 09:35
> In regular version: size of points shown in app are larger in the export

Currently the size of the points depends on the map zoom. Therefore, this might be related to the update of zoom and center and could be sovled when fixing the [above](https://github.com/Pandora-IsoMemo/iso-app/issues/24#issuecomment-1104949022).

Another fix would be to **only** use a fixed point size, e.g. the radius in km, no matter what is the current zoom, and to add an input to adjust the  point size.

**Comment by isomemo** [comment] 2022-04-21 09:59
@arunge you can remove the jitter and one could have the option to show clusters as you suggested. However, this should be optional and it should also be possible to show points (in this case points at the same location overlap and only one point is visible). Having the option to set the size of the points is part of the contract specification. It should be case that point size visualized in the app map matches that of the export.

**Comment by arunge** [comment] 2022-04-25 10:59
Regarding the bugs mentioned above, I prepared a pull request that fixes some of them (on the **beta** version). It is under review, now.

> In regular version: size of points shown in app are larger in the export
- This is related to the point size that depends on the zoom. When we implemented the fixed point sizes as discussed [here](https://github.com/Pandora-IsoMemo/iso-app/issues/24#issuecomment-1104991777) within https://github.com/Pandora-IsoMemo/iso-app/issues/13 this will disappear.

> Both versions: when show/hide north arrow/scale/logo the entire map is moved
- under review, fixed soon (https://github.com/Pandora-IsoMemo/iso-app/pull/26)

> weird behaviour with visibility of export button
- under review, fixed soon

> Beta version:
applying coordinate values should not be dynamic! Add an "Apply coordinates" button
the show/hide button is for the Pandora database square (a new logo has been added)
Most important when exporting a map a different area of the map is shown and the points are not visible (we had this bug before)
- under review, fixed soon

**Comment by arunge** [comment] 2022-04-29 12:03
The fixes were merged into the beta in version 22.04.4.
All was solved except:
> In regular version: size of points shown in app are larger in the export

This will be solved with 
> Option to fix the size of points displayed in interactive (currently point size depends on number of locations with same lat/long).

in https://github.com/Pandora-IsoMemo/iso-app/issues/13 and when the updates from the beta will be merged to the main.

**Closed by arunge** 2022-04-29 12:03 UTC
Labels: bug, Pandora and IsoMemo data tables
