### ISSUE TITLE
Error in SpreadR

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#10] opened 2022-02-28 17:59 UTC
Selected as data source "Lives" with all categories/fields also selected. Tried to run SpreadR model.

For Mean or lower time point: dateLower
For Standard deviation or upper time point selected: dateUpper

Remaining options as default. Ran model and got this error:

"Error in model fitting. Please check your input variables assignments and your data."

This was previously working!

**Comment by jroachell15** [comment] 2022-03-02 08:05
@isomemo we will retest this and come back with a more well-rounded response to this error. thanks Ricardo!

**Comment by arunge** [comment] 2022-03-03 08:48
We could reproduce this error, even on the previous version (1) from the former repository:

![image](https://user-images.githubusercontent.com/16759098/156529056-21af0955-36f6-47fc-933f-8cca7002b022.png)

![image](https://user-images.githubusercontent.com/16759098/156529153-dd7c1263-182c-4871-84c6-a200a923ba3a.png)

- We will look for the problem and fix it. It looks like an issue with default values.

**Comment by mgross** [comment] 2022-03-26 09:31
@jroachell15 @arunge @isomemo Sorry that was my fault. Should be fixed with 22.2.3

**Comment by arunge** [comment] 2022-03-28 08:33
I merged the [fix](https://github.com/Pandora-IsoMemo/iso-app/commit/514fa5c1e08ca667b59aa8e863a4b322818d01d3) from @mgross into the beta version, also.
I can confirm that the fix solves the problem in version 22.2.3.

@isomemo  I close here now.

**Closed by arunge** 2022-03-28 08:33 UTC
Labels: bug
