### ISSUE TITLE
[MPI_WP2]: 4. Kernel and KernelTimeR - Add a new clustering option

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#54] opened 2022-08-10 09:35 UTC
These models are available within the IsoMemo package (https://github.com/Pandora-
IsoMemo/iso-data/tree/main/R). They employ clustering analysis.

Add a new clustering option to the existing ones using the Mclust package. Mclust function to be used which automatically calculates the best fitting number of clusters.

In KernelTimeR one can display clusters by colour in a map plus “Time intervals by cluster”. However, currently the cluster colours in these two displays do not match. Make the colours match.

![Image](https://user-images.githubusercontent.com/73887426/183869325-5f06e040-dfee-4474-af89-7a0395aec04f.png)

![Image](https://user-images.githubusercontent.com/73887426/183869467-45311164-c528-4b7e-b454-a679bc5f82ff.png)

**Comment by f-lukas** [comment] 2023-02-15 09:16
@isomemo 

Today I discussed the implementation of mclust as a clustering option within our team. In the 3-dimensional case (KernelTimeR) we have two ideas how to use mclust.

Currently, using kmeans, the approach is as following: compute initial 2-dim clusters (spatial only), then compute the 3-dim density for each point, for each cluster define the point with the highest density as the cluster centre, finally compute the final cluster assingment via the distance of the point to the cluster centre.

Using mclust, we could either use a similar approach as above, but calculate the initial 2-dim cluster via mclust (also gives us the option to let mclust choose the optimal number of clusters). Then we would continue as before. Or, alternatively, we could use mclust to directly compute a 3-dim clustering (spatiotemporal). 

Could you tell us which of these two options best suits your use cases?

**Comment by isomemo** [comment] 2023-03-16 10:42
@f-lukas @mgross concerning the 3-D clustering it is necessary to have Marcus' opinion on this. Namely, if he thinks that this to be a good option. We can also allow the user to chose between the old and new options.

Something very important: for KernelTimeR after the clustering there is an algorithm designed by Marcus that identifies for each cluster the point that has the best "temporal coverage". This should be kept in place irrespective of the clustering choice that is done previously.

We should also discuss in a meeting the input options for both mclust and tclust

**Comment by f-lukas** [comment] 2023-03-21 14:45
@isomemo - When I discussed the options within the team back in February, I mainly asked Marcus for his opinion, with the result that both options were possible. 

With this in mind:
> Something very important: for KernelTimeR after the clustering there is an algorithm designed by Marcus that identifies for each cluster the point that has the best "temporal coverage". This should be kept in place irrespective of the clustering choice that is done previously.

I would suggest adding the option (alongside kmeans) to do the initial cluster calculation with mclust and then proceed as before (using the algorithm designed by marcus to identify the point with the best temporal coverage).

Currently, the way I implemented mclust is, that as input a range for the number of potential clusters must be selected. Then mclust automatically determines the optimal number of clusters within the range using the BIC criterion. I would be happy to discuss this in our meeting and discuss any additional inputs.

**Comment by f-lukas** [comment] 2023-03-28 14:01
@isomemo  - As discussed earlier, this will be available for testing in the next few days. Before that, I wanted to check the effect of changing dateType (single time vs interval). The difference is, that with single time only the one time point is taken as a reference and it is checked whether this reference time point falls within the specified cluster time range input. If this is the case, this observation is used for clustering. For the option interval, an average value is first calculated from the upper and lower limits. The procedure is then the same as for single time, in that it is checked whether this mean value falls within the specified cluster time range.

We had also discussed, that I implement, that the temporal cluster assignment is only done for the partial data that fall within the cluster time range. I have looked at this, but I am now of the opinion that this should not be changed. Maybe I didn't say it accurately earlier, but the algorithm to determine the temporal cluster centres is already only performed on the partial data. Only afterwards, the cluster assignment is determined for each observation, regardless of the time range. The advantage of this is that you can then decide whether you want to display only the partial data or all the data (can be selected on the right-hand side under Show Clustering > Show clustering all times or Show clustering time slice). The option Show Cluster all times would be obsolete if I now no longer determine the clusters for all data. However, as this is a practical functionality, I suggest to keep it. If you wish, I can insert a dummy column in the excel that indicates whether the observation lies within the cluster time range and was thus directly taken into account during clustering. Then it would be possible to filter according to this.

The calculation of lat_cluster_slice_centroid/long_cluster_slice_centroid is also only done on the partial data set. I would then proceed as with the temporal algorithm and then, after the cluster centres have been calculated on the basis of the partial data, also check for the other data points which cluster centre they are closest to and then assign them to this cluster.

I hope it is understandable why I am suggesting it this way. The code was already implemented this way, so nothing more would have to be changed. But please let me know if you prefer a different solution.

**Comment by isomemo** [comment] 2023-03-29 13:49
@f-lukas you have three options in date type:

1) Single point
2) Interval
3) Mean + SD

Nothing should be changed on the above! The procedure to calculate a single point when the options interval/Mean + SD are selected should be left as is. Indeed the result is then used to make clustering calculations using just one point.

If the clustering algorithm is only applying the modelling to filtered temporal data then indeed nothing should be changed.

I will write below my understanding of how things should work:

1) We have a set of original data points that may be further filtered according to their temporal range as described above. Let's call these "Filtered points" even if the full temporal range is used and none of the original data points is removed.
2) We have the points that are shown for a selected temporal slice and shown in the map. Let's call these "Slice points"
3) Clustering could be applied to "Filtered points" and separately to "Slice points"
4) I had understood from previous messages that you wanted to add clustering for the "Slice points" but now I understand that you were actually referring to the temporal filter option, correct? If so, let's drop the calculation of clustering for "Slice points".
5) When it comes to "Filtered points" we need to have the following outputs in the exported file:

a) Geographical centroid (lat/long) centroid for each cluster
b) Location of the selected point (lag/long) following the application of Marcus' temporal algorithm
c) For each row the identification of which cluster the row point belongs to
d) When exporting the file this will include all original rows. However, if a point was filtered out and not included in the clustering calculations you should leave the cell values empty.  

Thus in total, there would be 5 fields added to the export file (geo_centroid_lat, geo_centroid_long, temp_centroid_lat, temp_centroid_long, and cluster). Whenever rows/points were not used in clustering calculations the cells for the previous fields are left empty.

Important: 

1) On the right menu rename "Show all cluster locations" to "Cluster visibility". Within this change "Show clustering all times" to "Show points for all times" and change "Show clustering time slice" to "Show only points for time slice". This will make things clearer.
2) The colours of the clusters in the map were not matching the colours of the clusters for the option "Time intervals by cluster". When releasing the updated version please ensure that the colours match.

**Comment by isomemo** [comment] 2023-03-30 06:32
@f-lukas one change to what I said previously. I had said to leave cells empty for clustering values for rows that had been filtered out. But instead of this it is best not no include the entire row if this was filtered out. That is, in the export of the data with added clustering values include only the data rows that were selected after filtering.

**Comment by isomemo** [comment] 2023-03-31 16:02
@f-lukas no worries! I also think that I did not make something clear. You do not need to export fields for filtered and unfiltered data. I think that this implies that you have to do the clustering twice which makes the process slower.

1) Can you please confirm that clustering analysis is only done once? 
2) Can you please confirm that clusterin analysis is only done on filtered data?
2) We only need the lat/long fields for the filtered geometrical centroid and the temporal centroid. For all data, this is not needed (of course, if the user does not restrict the time rage this will be all data).
3) On the left side, for the mclust option, change "Number of clusters (optional)" to "Possible range for clusters"
4) Increase the maximum number of clusters from 20 to 50
5) I loaded the LiVES dataset and ran the KernelTimeR model using default options (using mclust) but the centroids in the exported Excel do not match those shown in the map.

Loaded data from LiVES

![image](https://user-images.githubusercontent.com/46485054/229170024-f10753d2-a653-4cf5-8f87-e00e10d7a9f7.png)

Clustering map results using mclust (just the centroids)

![image](https://user-images.githubusercontent.com/46485054/229170203-38dde43f-21ec-412c-9539-6ae28bf9e945.png)

Coordinates for centroids from Cluster 1

![image](https://user-images.githubusercontent.com/46485054/229170768-1bb4c827-75bf-49dc-bfbb-20565d735228.png)

But this centroid do not map where the IsoMemo map shows (in Belgium) but near Nuremberg in Germany

![image](https://user-images.githubusercontent.com/46485054/229171079-aaab41a0-173c-446b-ac11-2982eeafd3b9.png)

I also mapped the coordinates for the temporal centroid and this seems to match the geometrical centroid. Perhaps the labels are switched? See below.

![image](https://user-images.githubusercontent.com/46485054/229171820-ec7ad394-de1c-406a-8734-078cb8294c1a.png)

**Comment by isomemo** [comment] 2023-03-31 16:26
@f-lukas is another bug. For the same example described in the previous example, I made two changes: I increased the minimum number of clusters (to 12) and I applied a spatial filter (I set the upper longitude range restriction to 60 instead of the default value). However, the clustering result had only four clusters (not minimum 12) and the clustering number jumps from 3 to 5 without including 4. You can see this clearly below in the "Time intervals by cluster"

![image](https://user-images.githubusercontent.com/46485054/229176866-bba164e1-d9a3-4a18-a058-e857610aa4c6.png)

**Comment by arunge** [comment] 2023-04-05 09:24
@isomemo @f-lukas is currently on holiday, but he will return to you next week. Thanks, for you patience!

**Comment by isomemo** [comment] 2023-04-05 09:59
@arunge @f-lukas  Ok, I will wait for Lukas to return to fix the bugs and make the changes listed above. However, I changed my mind about the naming of export columns. To further clarify the issue I made the figure below.

![image](https://user-images.githubusercontent.com/46485054/230046872-1ad0c9cb-11a7-45d4-a0aa-6dbcca9a47b6.png)

When discussing the topic with Lukas I got confused on the issue of temporal filters. I thought that he was referring to the time slider that only shows points for the selected time. I wrongly understood that there would be a new clustering option only for visible points. This, however, is not needed.

As shown in the figure above, when using KernelTimeR there will be 5 added columns in the exported file. This file will only contain points that remained after the user applied temporal AND spatial filters. The clustering is done only on filtered points. Of course, if no filters are applied then the entire dataset will be used. The columns are:

the lat for geometrical centroid: cluster_geo_centroid_lat
the long for geometrical centroid: cluster_geo_centroid_long
cluster assignment: cluster_assignment
the lat for temporal centroid (Marcus' algorithm): cluster_temp_centroid_lat
the long for temporal centroid (Marcus' algorithm): cluster_temp_centroid_long

Of course, for KernelR there are no temporal centroids

**Comment by isomemo** [comment] 2023-04-16 11:06
@f-lukas @mgross 

1) Ok! So, now it is clear that kmeans or mclust clustering is applied to temporally and spatially filtered points plus we have set the final names for these in the export file.
2) I had assume that the map interface for KernelTimeR was showing the spatial (not temporal centroids). Firstly, please confirm that for KernelR the centroid shown is the spatial one (KernelR does not use temporal information). Secondly, in KernelTimeR please add the option to show either the spatial or temporal centroid via a radio button. This should be done for the interface section shown below (these options: a) Show only spatial centroids; b) Show only temporal centroids; c) Show points for all times; d) Show only points for time slice).

![image](https://user-images.githubusercontent.com/46485054/232301707-9c5a0f22-3eb4-4c18-ba76-7413ff7ae379.png)

3) Finally, and most importantly there should always be available a temporal centroid and bug instances cannot happen. The basic principle is that after clusters are spatially defined a site within each of these clusters is selected to be that that has better temporal coverage. To also comment on this I have included Marcus. This is the description of the heuristic that Marcus sent me previously:

![image](https://user-images.githubusercontent.com/46485054/232304100-4428851b-ac68-4815-bfa2-af1a3b42c20e.png)

Where it says that nearby could be defined as within kernel density bandwidth, is this the root of the issue? Can we redefine this so that nearby actually means all points within the cluster (as set by mclust/kmeans)?

Also, I noticed that B (standard deviation) is multiplied by A. Should this not be 1/B?

**Comment by f-lukas** [comment] 2023-04-21 15:28
@isomemo - All requested changes are now available in the beta app.

- removed the calculation of clusters for unfiltered data
- renamed columns in the excel export
- renamed "Number of clusters (optional)" to "Possible range for clusters"
- increased the maximum number of clusters from 20 to 50 for mclust
- added option to show spatial centroids

> Firstly, please confirm that for KernelR the centroid shown is the spatial one (KernelR does not use temporal information).

I can confirm that.

I can't answer your question to Marcus about the calculation. But the case you discovered here https://github.com/Pandora-IsoMemo/iso-app/issues/54#issuecomment-1492233899 is now very unlikely and only happens if  the cluster solution contains many many clusters e.g. close to 50.

**Comment by isomemo** [comment] 2023-04-21 16:57
@f-lukas @arunge @mgross 

Lukas, thanks for the feedback and all the updates.

There are still some bugs and important points!

1) Importantly, there should be no malfunction irrespective of the number of clusters. If k-means/mclust works and assigns clusters then it should be possible to select a site with optional chronological info. Besides not doing this is there any other type of error that may take place? What about my suggestion mentioned previously to you/Marcus?

2) The assignment is not working in the exported file. I used the LiVES dataset (using mclust and up to 50 clusters - it selected 31). Below you can see the exported data for cluster 22. There are different problems. Clearly, the points are not for cluster 22 since there are points from very different locations (e.g. Spain, Germany, UK) which according to the map belong to different clusters. Furthermore, for cluster 22 the coordinates for the geometrical cluster should always be the same but they are not. I did not check if the temporal cluster assignment is correct but I strongly suspect that it is not.

Clustering results
![image](https://user-images.githubusercontent.com/46485054/233691856-db26ac6d-90b9-481f-9340-c2991059834b.png)

Points identified in the exported Excel as belonging to cluster 22 but actually are from very different locations

![image](https://user-images.githubusercontent.com/46485054/233692123-49df831c-265b-40ca-a87d-6920c9348714.png)

Different values for geometric centroids

![image](https://user-images.githubusercontent.com/46485054/233692355-39a0d7ff-b142-4e8d-b67a-b409c3aed3d0.png)

3) @arunge I reported in a previous post an issue with the data import module. This happened after using KernelTimeR on the LiVES dataset and then trying to use the data import module. If I use directly the data import module it works fine. I have no idea if this may be related with the issues I mentioned above but I suspect not.

**Comment by f-lukas** [comment] 2023-04-23 15:03
> The assignment is not working in the exported file.

The assignment (cluster id, first column in the excel) belongs to the cluster centers determined via the temporal algorithm (column D and E in the excel, cluster_temp_centroid_lat and cluster_temp_centroid_long) and not to columns B and C. This is how it was before and how it is still the case in the main app. B und C are the columns you wanted me to add (cluster_geo_centroid_lat and cluster_geo_centroid_long). 
The assignment is not the same for the temporal centroids (column D and E) and geometrical centroids (column B and C). The reason for this is how the entire clustering process works. I have described it shortly in this comment https://github.com/Pandora-IsoMemo/iso-app/issues/54#issuecomment-1507092401 but will try to do it in more detail now.
 The clustering is done on the filtered dataset, using kmeans or mclust. This step selects n centroids which we call geometrical centroids (columns B and C in the excel). In the excel, every point with the same value in column B and C belongs to the same cluster determined through this inital clustering step. After this step, the temporal algoirthm is used. Firstly, for every cluster from the previous step, a new cluster center is determined (by using the point with the highest density taking the temporal aspect into account). We then have n new cluster centers (these are the values in column D and E). Now, the final assignment of the points to the temporal clusters is determined (column A). To do this, for every point, the distance to the temporal cluster centers is measured. The point is assigned to the cluster with the smallest distance. Because of this, two points that belonged to the same cluster after the inital clustering, can now be in different clusters (depending on their temporal value).

**Comment by isomemo** [comment] 2023-04-23 15:41
@f-lukas @arunge @mgross 

This method seems to be quite different from the one that I discussed with Marcus:

1) As with KernelR clusters are assigned and geographical centroids calculated
2) A heuristic is applied to choose a site within each cluster which has  the "best" temporal data (temporal centroids)
3) Nothing else is done. The clusters remain those defined as per point 1. This is why I said that the changes should be quite simple.

I need to understand why Marcus implemented an option that "creates new" clusters. If this is indeed a better option we will have to modify the texts in the interface so that cluster definition and centroid definition are clear to users.
I also need to understand why in some circumstances a bug may be issued, even if this is rare so that this can be solved.

**Comment by f-lukas** [comment] 2023-04-23 15:54
> I also need to understand why in some circumstances a bug may be issued, even if this is rare so that this can be solved.

Here is an example: Imagine the dataset is rather small and the user selects mclust with a potential range of 48 to 50 clusters. Mclust finds the best solution is with 48 clusters. Now we have 48 clusters with only a few points within each cluster. Now the temporal algorithm determines 48 new cluster centers. Then for every point the distance to the cluster centers is measured. Now it can happen that all points are assigned to (for example) only 45 cluster centers, because 3 cluster centers are so far away that no point is closest to this cluster. This yields to the case that there are only 45 clusters despite the user wanted 48 to 50.

**Comment by isomemo** [comment] 2023-04-23 16:00
@f-lukas @mgross @arunge 
I have sent an email to Marcus and cc'ed you. The problem is that we actually have a new clustering step that I was not aware took place. In your example, we actually have 45 clusters following the temporal modelling. Not only I did not realize this but the map shows the geographical clusters. So, this causes confusion.

I just want to hear from Marcus a justification for the approach. Following this, the easiest solution will be just to show in the map the final temporal clusters (we will also no longer need geometrical centroids in the export) and change some of the options/text in the interface to have things clearer for the user.

**Comment by isomemo** [comment] 2023-05-19 14:49
@f-lukas 

Point 1)

You are correct on the text below (I made a writing mistake):

    long_temporal_group_reference_point: long of reference point for temporal groups
    lat_temporal_group_reference_point: lat of reference point for temporal groups
    long_centroid_spatial_cluster: long of reference point for spatial cluster
    lat_centroid_spatial_cluster: lat of reference point for spatial cluster

Point 2)

I meant that the result will be the same as for KernelR if no filtering is applied to the data used for KernelTimeR

Point 3) I accept your sugestion.

**Comment by f-lukas** [comment] 2023-05-22 08:50
@isomemo - Thank you for the quick feedback. Then I have now understood all the points. I need between 2 and 5 hours for the changes including some testing. It depends on whether the changes, such as renaming, require any additional adjustments.

**Comment by isomemo** [comment] 2023-05-22 08:54
@f-lukas thanks! Please go ahead and prioritize implementing this as soon as possible.

**Comment by f-lukas** [comment] 2023-05-24 12:06
@isomemo - The changes are now available for testing in the beta app.

![Bildschirmfoto vom 2023-05-24 14-04-47](https://github.com/Pandora-IsoMemo/iso-app/assets/86153843/5463be8e-8569-4575-9c1b-1a9a8cea4dc6)

**Comment by isomemo** [comment] 2023-05-24 12:21
@f-lukas 

I tested this using the same LiVES dataset.

Result for Temporal Grouping
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/75795ceb-9662-4db2-b670-925c1ccb5625)

Result for Spatial Clustering
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/3db0721b-1e92-4890-977a-770afc7445e2)


As you can see from the above Temporal grouping has more clusters (up to 16).

Now the results for Time intervals by temporal group or cluster.

For Temporal Grouping

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/ebf6d795-9b87-42c4-8828-4301a8d4a3cc)


For Spatial clustering

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/a447d5a4-49c0-4de6-b96b-b00d8ba5aa9b)


For both options there are 10 "clusters" being shown but clearly there are "clusters" missing from the spatial option.

The same problem takes place for the exported Excel file. As you can see below there are only 10 different types of temporal groupings.
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/ed1e9552-c157-489f-8923-e6c13e916bba)

**Comment by isomemo** [comment] 2023-05-24 12:22
@f-lukas please ignore my previous message. My eyesight was the problem.

**Comment by arunge** [comment] 2023-05-31 12:22
@isomemo Do you have any comments regarding the integration of Mclust, or can we close here?

**Closed** 2023-07-11 10:23 UTC
Labels: IsoMemo App, User Story, 2022-WP2-4
