### ISSUE TITLE
SpreadR model fitting error

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#31] opened 2022-05-03 15:28 UTC
#30 this is related to the previous issue and dataset. To check why rather early date estimates are being generated I added a new column with entry values all set to 1000. I then used a single point model and selected the "1000" field as the single date input. I got the following error:

"Error in model fitting. Please check your input variables assignments and your data."

**Comment by mgross** [comment] 2022-05-07 09:30
On the bug: If you put only the same times into the data sets the model is going to fail (you cannot estimate any uncertainty from it),

First of all earlier dates are a feature of the model and are there by purpose/construction. I think we discussed this several times before but the modeling approach goes beyond simple interpolation by trying to estimate the minima and not the interpolated average of the observed times. So the true minima is very likely lower than the any of the observations, because when you collect a lot of additional data you will very likely find a date that is lower than what you already have. The model accounts for that and that is an important feature. As explained in the word document I send you the model assumes that the minima curve is a certain quantile (e.g. 5%) shifted by some amount "delta" (which is estimated). You can give prior information and give a minima such as -5000 for the rice data and then delta is set such that the minima does not go below -5000.

**Comment by isomemo** [comment] 2022-05-07 09:44
Can we please have a message stating that "All entry values are the same! No uncertainty estimate is possible!" when the same time is set for all inputs?

Yes, we discussed several times the spread modelling and the issues indicated by others are points I had raised before. Just wondering if there would be any further recommendations before moving on to Adam's modelling. 

Can you please clarify the following:

We have this message in the quantile selection: "Exceeding quantile (e.g. .1% quantile as replacement for min)"

What is meant by exceeding quantile?
Are the values in the selector representing percentages (e.g. 0.05 = 5%)?

**Comment by arunge** [comment] 2022-06-15 08:44
@mgross @isomemo Is there any not-model related issue here where I could help? If yes, please just reassign me. :slightly_smiling_face:

**Comment by arunge** [comment] 2023-06-12 09:41
@isomemo Regarding:

> Can we please have a message stating that "All entry values are the same! No uncertainty estimate is possible!" when the same time is set for all inputs?

I will implement the message "All entry values are the same! No uncertainty estimate is possible!" and than all will be solved here? Or are there any other open questions regarding SpreadR (see the comment [above](https://github.com/Pandora-IsoMemo/iso-app/issues/31#issuecomment-1120176908)) where @mgross should help?

**Comment by arunge** [comment] 2023-07-11 11:08
@isomemo As discussed you wanted to check this issue, especcially https://github.com/Pandora-IsoMemo/iso-app/issues/31#issuecomment-1120174726 and https://github.com/Pandora-IsoMemo/iso-app/issues/31#issuecomment-1120176908 when you find time.

**Comment by arunge** [comment] 2024-04-09 11:24
This issue is deprecated and possibly not reproducible . If we observe issues with the current implementation, we will open separate issues.

**Closed by arunge** 2024-04-09 11:24 UTC
Labels: bug, question, IsoMemo App
