### ISSUE TITLE
Yet another error on SpreadR

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#18] opened 2022-03-27 14:43 UTC
I tried to run SpreadR and got this error when selecting for Date type "Single point" or "Mean + 1SD uncertainty":

"Error in model fitting. Please check your input variables assignments and your data."

The above was working previously I am rather concerned that several things stopped working under the new transition and I just noticing now a few of them. We will need to chat about this.

**Comment by arunge** [comment] 2022-03-28 08:37
Duplicate of https://github.com/Pandora-IsoMemo/iso-app/issues/16

**Closed by arunge** 2022-03-28 08:37 UTC
Labels: bug
