### ISSUE TITLE
[tasks 2022]: Separate skin with limited functions and limit user resources for interface with all options

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#9] opened 2022-02-28 12:59 UTC
original here: https://github.com/isomemo/mpi-iso-app/issues/127

> Install a replicate of the isomemo interface in a separate server. This will have all download options but only the isomemo app available. For the isomemo app only the first two tabs (Data and “Interactive map) will be available.
> For the complete interface, options that I can set via a text script on upper limit for memory and CPU for a single user running the isomemo models.
> 
> _____________________________________________________________________________________________
> INWT Comments (November 2, 2021):
> We kindly ask you to implement this with a third party. As already discussed, we can add an option to the app to hide all tabs with exception of the first two. The deployment should be carried out by someone else, who can take over the operations part in the future.
> SUPPORT: We can prepare the app, can modify the apps and can help set up the admin hosting consulting in the support contract (timebank), MPI is responsible for implementation for this. We can have an initial session to set up. 
> 
> INWT Comments: (Feb 1, 2022) we are confident that we can do this tasks without external help. 
> 

----
from https://github.com/isomemo/mpi-iso-app/issues/127#issuecomment-1028023789:
> I discussed the settings with @wahani today. He suggested another settup:
> - we use an environmental variable that tells to hide the modeling tab
> - we don't need a second branch -> less deployment
> - we add the option to switch between versions to the master and depl branch and change the environmental variable on the shiny proxy server itself. Here @wahani will support.
> 
> In summary, this is less work and easier to maintain.
> 
> - [x] I prepared this feature which @wahani will review
> - ~at the moment @wahani has no access to this repository, so first @isomemo needs to grant him the rights.~
> - [x] add this feature (in the new repo: https://github.com/Pandora-IsoMemo/iso-app)
> - [x] It will be available after redirecting app to the new repo
> - [x] second app will be toggled via the global variable: "ISOMEMO_HIDE_MODELLING"

**Comment by arunge** [comment] 2022-02-28 13:01
The option to set the variable "ISOMEMO_HIDE_MODELLING" was implemented, the app is now running on this new repository.

@wahani Could you set up a second app without the moddeling? Do you need help from my side here?

**Comment by wahani** [comment] 2022-03-01 13:08
@arunge can you check if https://isomemoapp.com/app/iso-memo-data-app-beta is what you expect to see?

Final question what name should we use on https://isomemoapp.com for this app?

**Comment by arunge** [comment] 2022-03-02 11:53
@wahani the app is working as expected: after loading all data, the modelling tab is hidden, and instead a tab with the download button shows up.

@isomemo Could you suggest a name for the IsoMemo app "light" (which does not contain modelling) that we can use on https://isomemoapp.com/ ?
Is the current implementation under https://isomemoapp.com/app/iso-memo-data-app-beta
what you expected?

**Comment by arunge** [comment] 2022-04-26 11:10
As just discussed with @isomemo : Update the display name of the app(s):

![image](https://user-images.githubusercontent.com/16759098/165285795-557da604-9d13-47c6-bb03-ad1b12fecaff.png)

- in case of limited functions: "Data search"
- in case of full app: "Data search & Spatiotemporal modeling"

@isomemo 
- you mentioned you wanted to replace the download button with a link to the readme with instructions for downloading? Is that 
right?
- Can you provide a better name for the link to the app than: "**iso-memo-data-app-beta**" which is currently used: https://isomemoapp.com/app/iso-memo-data-app-beta ?
- And which one should be used here:
![image](https://user-images.githubusercontent.com/16759098/165287391-c6ebfb37-e84d-4f53-bd8a-99ab57fe58cb.png)

**Comment by arunge** [comment] 2022-05-10 12:04
@isomemo Currently we use the following url for the app version without modeling: https://isomemoapp.com/app/iso-memo-data-app-beta

You mentioned one that contains "search". Could you repeat your suggestion, please?

**Comment by isomemo** [comment] 2022-05-10 12:09
There will be two urls pointing to the server app: pandoradatasearch.earth and isomemodatasearch.com 

the title within the app could be: Pandora & IsoMemo data search

**Comment by arunge** [comment] 2022-05-20 10:14
@isomemo I am updating the tab panel for the _only-data-search-mode_ of the app. I remove the download button and show the following text and links with the next version. Is this text ok? Or do you suggest something else?

![image](https://user-images.githubusercontent.com/16759098/169506601-4a7973ab-458b-4c3f-989e-9c7582a43625.png)

**Comment by arunge** [comment] 2022-06-14 14:45
@isomemo I updatet the titles and the tab with the link to the model, see [above](https://github.com/Pandora-IsoMemo/iso-app/issues/9#issuecomment-1132730666) for the two app versions with version 22.6.2 on the main and beta branch. Currently, you can see both versions under:
- **light app:** https://isomemoapp.com/app/iso-memo-data-app-beta
- **full app:** https://isomemoapp.com/app/iso-memo-app-beta

## What is left: set up the new urls
@wahani already contacted your IT and will guide on the next steps.

**Comment by wahani** [comment] 2022-06-27 11:11
Quick update on the progress:

- We have now access to the new server
- Accounts/VPN have been configured by MPI and access was verified by me
- MPI IT have encountered an issue on the DB server, which was caused by an automatic backup und too many orphaned docker images. INWT has resolved these issues. It is likely that they are the root cause of https://github.com/Pandora-IsoMemo/iso-api/issues/1 and recent issue with https://github.com/Pandora-IsoMemo/bpred not being available
- We may now proceed and deploy the new app

**Comment by jroachell15** [comment] 2022-08-02 14:16
@isomemo 

### **We do have the "online data search app" implemented. You can access the web app here: https://isomemoapp.com/app/iso-memo-data-app-beta**

let me know if you have any questions. if not @wahani we can close this ticket. thanks!

**Comment by isomemo** [comment] 2022-08-03 10:33
@wahani @jroachell15 

There are two points here:

1) I had requested the development of a Pandora & IsoMemo interface that should mirror whatever our default Pandora & IsoMemo interface but that should not include modelling options. The link that you sent correspond to this but it mentions beta and so I assume that this is for the beta version. I should have the link for the "official public" app.

2) The above should be installed in a separate server and you had a meeting about this with our IT. There are two addresses pointing to that server (https://isomemosearch.com/ and https://pandorasearch.earth/) but when I use these I do not get the app interface.

Can you please:

a) give me the link for the official public app
b) please confirm that this app is installed in a separate server (this server only hosts this app)
c) once you give the link I will ask our IT to redirect our addresses to that. Let me know if you have any comments on this

**Comment by wahani** [comment] 2022-08-09 07:41
@isomemo you are correct. The new server is not in use yet. I will post any updates here as soon as shinyproxy, etc is running on the new machine.

**Comment by isomemo** [comment] 2022-08-09 08:59
@wahani Thanks!

**Comment by wahani** [comment] 2022-08-17 12:29
@isomemo some updates for your review:

- The server is now running and the App is available at https://pandorasearch.earth/ and https://isomemosearch.com/
- We only have access to one app, that is is isomemo app with the limited GUI as described/developed by @arunge (https://github.com/Pandora-IsoMemo/iso-app/issues/9#issuecomment-1132730666)
- The server will receive maintenance tasks (docker prune) by Jenkins (happens every day automatically) and is otherwise maintained by the MPI IT.
- The server will receive new docker images, aka new versions of the app, as soon as they are released. Happens automatically.
- I have recycled the same landing page from isomemoapp.com 

Please let me know if we need any changes to the name of the service and/or app:

![grafik](https://user-images.githubusercontent.com/3105646/185120338-78d28916-c7f7-4966-8f61-145d6c5b00f9.png)

**Comment by isomemo** [comment] 2022-10-06 09:47
@wahani @arunge 

The link should forward directly to the search app. Showing first the logo of the app (as in the figure in the previous post is redundant in this case as we only have one option)

While loading the following message is shown:

![image](https://user-images.githubusercontent.com/46485054/194277926-0e517b60-ec96-4b0a-ad1a-b457b36b9cdb.png)

This should be rephrased to "Launching Pandora & IsoMemo Data Search"

Under the modelling tab, we have the following text 

![image](https://user-images.githubusercontent.com/46485054/194278155-98f05821-a6a5-4c3f-afac-d6468ff14554.png)

To access Pandora & IsoMemo modelling please:

- Visit https://pandoraapp.earth or https://isomemoapp.com/ [this may be slow]. There you can select the option Data Search and Spatiotemporal modelling

or

- Install apps locally. General installation instructions are available at https://github.com/Pandora-IsoMemo/drat . Installation instructions for the Data Search and Spatiotemporal Modelling app are available at [ADD here the appropriate link]

**Comment by wahani** [comment] 2022-10-17 12:29
@isomemo I prepared the following changes:

- apps are now directly accessible at  https://pandorasearch.earth/ and https://isomemosearch.com/ (no landing page)
- The display name is now changed to *Launching Pandora & IsoMemo Data Search*

@arunge I leave the other changes in the modelling tab to you.

**Comment by arunge** [comment] 2022-10-21 11:12
@isomemo I pushed a [new version](https://github.com/Pandora-IsoMemo/iso-app/pull/74#issue-1418137748) to the main app. Please, check the updated text in the modeling tab of the [_Search App_](https://pandorasearch.earth/) and let me know if all is fine.

**Comment by isomemo** [comment] 2022-12-02 10:39
@arunge looks good!

**Comment by isomemo** [comment] 2022-12-02 10:39
@arunge looks good!

**Closed by isomemo** 2022-12-02 10:39 UTC
Labels: 2022: Separate skin to limit functions, IsoMemo App
